packages/financial-contracts/abis/ExpiringMultiParty.json
packages/financial-contracts/schema.graphql
packages/financial-contracts/src/mappings/registry.ts
packages/financial-contracts/src/utils/constants.ts

Adds:
- minSponsorTokens: BigDecimal
- disputeBondPercentage: BigDecimal
- sponsorDisputeRewardPercentage: BigDecimal
- disputerDisputeRewardPercentage: BigDecimal
- withdrawalLiveness: BigInt
- liquidationLiveness: BigInt
- priceIdentifier: String

Add params to FinancialContract schema

---

packages/voting/manifest/data/kovan.json

New IDWhitelist was deployed recently.
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

feat(voting): Update Kovan IdentifierWhitelist

---

packages/long-short-pair/manifest/data/kovan.json
packages/long-short-pair/manifest/data/mainnet.json
packages/long-short-pair/manifest/data/polygon.json

Signed-off-by: Christopher Maree <christopher.maree@gmail.com>

feat(lsp): Add kovan, mainnet and polygon addresses for new deployments

---

packages/optimistic-oracle/manifest/data/mainnet.json
packages/optimistic-oracle/manifest/data/polygon.json

New deployments that used the compile optimizer with 1mil runs.
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

feat(optimistic-oracale): Update addresses

---

packages/votingV2/.gitignore
packages/votingV2/manifest/data/goerli.json
packages/votingV2/manifest/templates/addresses.template.ts
packages/votingV2/scripts/build-manifest.sh
packages/votingV2/src/utils/constants.ts
packages/votingV2/src/utils/helpers/votingToken.ts

feat: remove addresses from constants file

---

packages/votingV2/src/mappings/votingV2.ts
packages/votingV2/src/utils/decimals.ts

- Fix div by 0 errors
Deployed here: https://api.thegraph.com/subgraphs/name/md0x/votingv2-version-79

fix: div by zero errors

---

packages/votingV2/manifest/data/goerli.json
packages/votingV2/manifest/templates/VotingV2.template.yaml
packages/votingV2/src/mappings/votingV2.ts

-  Deploy a new VotingV2 contract
-  Update abi and event signatures

feat: add goerli deployment

---

packages/votingV2/src/mappings/votingV2.ts

- Fix the staking boolean logic

fix: staking bool

---

packages/votingV2/manifest/data/goerli.json

- Add new VotingV2 contract address

feat: add new voting v2 goerli address

---

README.md
packages/optimistic-oracle-v2/package.json
packages/optimistic-oracle-v2/scripts/deploy.sh
packages/optimistic-oracle-v2/src/mappings/optimisticOracleV2.ts
packages/optimistic-oracle-v2/src/utils/helpers/optimisticOracle.ts
packages/optimistic-oracle-v3/package.json
packages/optimistic-oracle-v3/scripts/deploy.sh
packages/optimistic-oracle/package.json
packages/optimistic-oracle/scripts/deploy.sh
packages/votingV2/manifest/data/goerli.json
packages/votingV2/manifest/data/mainnet.json
packages/votingV2/package.json
packages/votingV2/scripts/deploy.sh
scripts/deploy.sh

Updated the names and deployed the following subgraphs:
This subgraph indexes events emitted by the core Oracle contracts. The code can be found in `packages/votingV2`
- Mainnet: https://thegraph.com/hosted-service/subgraph/umaprotocol/mainnet-voting-v2
- Goerli: https://thegraph.com/hosted-service/subgraph/md0x/goerli-voting-v2
- Mainnet: https://thegraph.com/hosted-service/subgraph/umaprotocol/mainnet-optimistic-oracle
- Polygon: https://thegraph.com/hosted-service/subgraph/umaprotocol/polygon-optimistic-oracle
- Arbitrum: https://thegraph.com/hosted-service/subgraph/umaprotocol/arbitrum-optimistic-oracle
- Optimism: https://thegraph.com/hosted-service/subgraph/umaprotocol/optimism-optimistic-oracle
- Boba: …

feat: update subgraph naming and deployements

---

packages/optimistic-oracle-v3/schema.graphql

- Make `assertionTimestamp` non-nullable

feat: non-nullable assertionTimestamp

---

packages/skinny-optimistic-oracle/schema.graphql
packages/skinny-optimistic-oracle/src/mappings/skinnyOptimisticOracle.ts

- Add price request state in skinny subgraph

feat: add price request state in skinny subgraph

---

packages/optimistic-oracle-v2/src/mappings/optimisticOracleV2.ts

Update oov2 to consider goerli network.

feat: update oov2 to consider goerli

---

packages/votingV2/src/mappings/votingV2.ts

- Update latest round in commit

feat: update latest round commit

---

packages/optimistic-governor/README.md
packages/optimistic-governor/manifest/data/goerli.json
packages/optimistic-governor/schema.graphql
packages/optimistic-governor/src/mappings/optimisticGovernor.ts

Deploy the OG subgraph in goerli
Add explanationText param with the explanation as a utf8 string
Fixes UMA-1619

feat: add goerli and explanation text

---

README.md
packages/optimistic-governor/README.md
packages/optimistic-governor/schema.graphql
packages/optimistic-governor/src/mappings/optimisticGovernor.ts

- Change proposal id to be equal to the assertionId
- Deploy subgraphs

feat: update og proposal id and deploy umaprotocol namespace

---

README.md

- Deployed official versions of the oov3 subgraph in gnosis and avalanche

feat: deploy official versions of the oov3 subgraph in gnosis and avalanche

---

packages/optimistic-governor/schema.graphql
packages/optimistic-governor/src/mappings/optimisticGovernor.ts
packages/optimistic-governor/src/utils/helpers/optimisticGovernor.ts

feat: handle og deleted proposals

---

README.md
packages/optimistic-governor/README.md
packages/optimistic-governor/manifest/data/core.json
packages/optimistic-governor/package.json
packages/optimistic-governor/src/mappings/optimisticGovernor.ts
packages/optimistic-oracle-v2/README.md
packages/optimistic-oracle-v2/manifest/data/core.json
packages/optimistic-oracle-v2/package.json
packages/optimistic-oracle-v3/README.md
packages/optimistic-oracle-v3/manifest/data/core.json
packages/optimistic-oracle-v3/package.json
packages/optimistic-oracle/README.md
packages/optimistic-oracle/manifest/data/core.json
packages/optimistic-oracle/package.json

Adding Core mainnet deployments for Optimistic Oracle and Optimistic Governor subgraphs.
Fixes: https://linear.app/uma/issue/UMA-2056/subgraph-deployments

feat: core mainnet deployments

---

README.md
packages/optimistic-oracle-v2/README.md
packages/optimistic-oracle-v2/manifest/data/base.json
packages/optimistic-oracle-v2/package.json
packages/optimistic-oracle-v3/README.md
packages/optimistic-oracle-v3/manifest/data/base.json
packages/optimistic-oracle-v3/package.json
packages/optimistic-oracle/README.md
packages/optimistic-oracle/manifest/data/base.json
packages/optimistic-oracle/package.json
scripts/deploy.sh

Adds Optimistic Oracle subgraphs for Base.
As hosted service does not support Base, only on Studio, this also changes deploy script to allow studio deployments.
Fixes: https://linear.app/uma/issue/UMA-2472/subgraph-deployments

feat: base optimistic oracle

---

README.md
packages/optimistic-governor/README.md
packages/optimistic-governor/manifest/data/base.json
packages/optimistic-governor/package.json
packages/optimistic-governor/src/mappings/optimisticGovernor.ts
scripts/deploy.sh

- Deploy Base Mainnet Optimistic Governor subgraph

feat: deploy base mainnet optimistic governor subgraph

---

README.md
packages/optimistic-oracle-v2/README.md
packages/optimistic-oracle-v2/manifest/data/blast.json
packages/optimistic-oracle-v2/package.json
packages/optimistic-oracle-v3/README.md
packages/optimistic-oracle-v3/manifest/data/blast.json
packages/optimistic-oracle-v3/package.json
packages/optimistic-oracle/README.md
packages/optimistic-oracle/manifest/data/blast.json
packages/optimistic-oracle/package.json

Adds Optimistic Oracle subgraphs on Blast

feat: oo blast deployments

---

README.md

- Add backup graph urls for the OOv2 Polygon and OOv3 Base

feat: add new deployments to readme

---

README.md
packages/optimistic-oracle-v3/manifest/data/blast-goldsky.json
packages/optimistic-oracle-v3/package.json

Add goldsky deployments for oo v3

feat: add v3 goldsky scripts and deployments

---

packages/votingV2/schema.graphql
packages/votingV2/src/mappings/votingV2.ts
packages/votingV2/src/utils/helpers/voting.ts

- Fix memory issues voting v2 subgraph

fix: memory issues voting v2

---

README.md
packages/votingV2/src/mappings/votingV2.ts

PR description:
- Correct `totalTokensCommitted` by replacing commit-time estimate with exact stake on reveal

fix(voting-v2): total commited votes
